language: python
python:
  - "3.6"

branches:
  only:
  - mkdocs_blog

notifications:
  email:
    recipients:
      - zhang.guohao@qq.com
    on_success: always # default: change
    on_failure: always # default: alway
cache:
  directories:
  - build
  yarn: true

before_install:
   - export TZ='Asia/Shanghai'  # 设置时区
   - openssl aes-256-cbc -K $encrypted_889ea77ee21e_key -iv $encrypted_889ea77ee21e_iv -in github_deploy_key.enc -out ~/.ssh/github_deploy_key -d
   - chmod 600 ~/.ssh/github_deploy_key
   - eval $(ssh-agent)
   - ssh-add ~/.ssh/github_deploy_key

install:
   - pip install -r blog.requirement
script:
   - mkdocs build -c

after_script:
   - cd site/
   - touch CNAME
   - echo 'aisky.men' > CNAME
   - git init
   - git config user.name "zhishengqianjun"
   - git config user.email "zhishengqianjun@163.com"
   - git add .
   - git commit -m "Update sphinx By TravisCI With Build $TRAVIS_BUILD_NUMBER"
   - git push --force --quiet "https://zhishengqianjun:${CO_TOKEN}@${CO_REF}" master:master
   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF_IO}" master:master
   - scp -oStrictHostKeyChecking=no  -i ~/.ssh/github_deploy_key ../deploy.sh ${SERVER_USER}@${SERVER_IP}:~/deploy.sh
   - ssh -oStrictHostKeyChecking=no -i ~/.ssh/github_deploy_key ${SERVER_USER}@${SERVER_IP} "sh ~/deploy.sh"

env:
 global:
   # Coding Pages
   - CO_REF: git.dev.tencent.com/zhishengqianjun/blog.git
   - GH_REF: github.com/gaviners/mkdocs_blog.git
   - GH_REF_IO: github.com/gaviners/gaviners.github.io.git

